### ISSUE TITLE
docker image does not start with docker-compose, throwing error "Invalid MQTThost"

### ISSUE THREAD

**Issue by universal-dilettant** [theengs/gateway#175]
**Describe the bug**
TheengsGateway throws error "Invalid MQTT host" when started with docker-compose, despite mqtt host environment variable being existant and valid

**To Reproduce**

1. Data processed
```
docker-compose.yaml
        theengs:
                image: theengs/gateway
                network_mode: "host"
                environment:
                        - MQTT_HOST=127.0.0.1
                        - MQTT_USERNAME=uuuu
                        - MQTT_PASSWORD=####
                        - MQTT_PUB_TOPIC=TheengsGateway/BTtoMQTT
                        - MQTT_SUB_TOPIC=TheengsGateway/BTtoMQTT/set
                        - MQTT_PRE_TOPIC=TheengsGateway/BTtoMQTT
                        - LWT_TOPIC=TheengsGateway/LWT
                        - PUBLISH_ALL=true
                        - PUBLISH_ADVDATA=false
                        - TIME_BETWEEN=60
                        - SCAN_TIME=60
                        - LOG_LEVEL=INFO
                        - HAAS_DISCOVERY=false
                        - DISCOVERY=false
                        - DISCOVERY_TOPIC=homeassistant/sensor
                        - DISCOVERY_DEVICE_NAME=TheengsGateway
                        - DISCOVERY_FILTER="[TP357]"
                        - SCANNING_MODE=active
                        - ADAPTER=hci0
                volumes:
                        - "/var/run/dbus:/var/run/dbus"
                depends_on:
                        - mosquitto
                        - influx
```

2. Expected data

3. See error
```# docker-compose up theengs
X_mosquitto_1 is up-to-date
X_influx_1 is up-to-date
Starting X_theengs_1 ... done
Attaching to X_theengs_1
theengs_1    | Creating config at /root/theengsgw.conf ...
theengs_1    | {
theengs_1    |     "host": "127.0.0.1",
theengs_1    |     "pass": "####",
theengs_1    |     "user": "uuuu",
theengs_1    |     "port": 1883,
theengs_1    |     "publish_topic": "TheengsGateway/BTtoMQTT",
theengs_1    |     "subscribe_topic": "TheengsGateway/BTtoMQTT/set",
theengs_1    |     "presence_topic": "TheengsGateway/BTtoMQTT",
theengs_1    |     "presence": false,
theengs_1    |     "publish_all": true,
theengs_1    |     "publish_advdata": false,
theengs_1    |     "ble_scan_time": 60,
theengs_1    |     "ble_time_between_scans": 60,
theengs_1    |     "log_level": "INFO",
theengs_1    |     "lwt_topic": "TheengsGateway/LWT",
theengs_1    |     "discovery": false,
theengs_1    |     "hass_discovery": true,
theengs_1    |     "discovery_topic": "homeassistant/sensor",
theengs_1    |     "discovery_device_name": "TheengsGateway",
theengs_1    |     "discovery_filter": ""[TP357]"",
theengs_1    |     "scanning_mode": "active",
theengs_1    |     "adapter": "hci0",
theengs_1    |     "time_sync": "[]",
theengs_1    |     "time_format": "0"
theengs_1    | }
theengs_1    | Invalid MQTT host
X_theengs_1 exited with code 1
```

**Expected behavior**
Running image

**Screenshots**

**Environment**
Output of `python -m TheengsGateway.diagnose` or `python -m TheengsGateway.diagnose -c path_to_conf_file` if not using the default path for the configuration file.

Not available in docker image??

**Additional context**
When starting directly from command line, all ist fine
```
# docker run --rm \
    --network host \
    -e MQTT_HOST=127.0.0.1 \
    -e MQTT_USERNAME=uuuu \
    -e MQTT_PASSWORD=\#\#\#\# \
    -e MQTT_PUB_TOPIC=TheengsGateway/BTtoMQTT \
    -e MQTT_SUB_TOPIC=TheengsGateway/BTtoMQTT/set \
    -e MQTT_PRE_TOPIC=TheengsGateway/BTtoMQTT \
    -e PUBLISH_ALL=true \
    -e PUBLISH_ADVDATA=false \
    -e TIME_BETWEEN=60 \
    -e SCAN_TIME=60 \
    -e LOG_LEVEL=INFO \
    -e HAAS_DISCOVERY=true \
    -e DISCOVERY=false \
    -e DISCOVERY_TOPIC=homeassistant/sensor \
    -e DISCOVERY_DEVICE_NAME=TheengsGateway \
    -e DISCOVERY_FILTER="[TP357]" \
    -e SCANNING_MODE=active \
    -e ADAPTER=hci0 \
    -v /var/run/dbus:/var/run/dbus \
    --name TheengsGateway \
    theengs/gateway

Creating config at /root/theengsgw.conf ...
{
    "host": "127.0.0.1",
    "pass": "####",
    "user": "uuuu",
    "port": 1883,
    "publish_topic": "TheengsGateway/BTtoMQTT",
    "subscribe_topic": "TheengsGateway/BTtoMQTT/set",
    "presence_topic": "home/presence/TheengsGateway",
    "presence": false,
    "publish_all": true,
    "publish_advdata": false,
    "ble_scan_time": 60,
    "ble_time_between_scans": 60,
    "log_level": "INFO",
    "lwt_topic": "home/TheengsGateway/LWT",
    "discovery": false,
    "hass_discovery": true,
    "discovery_topic": "homeassistant/sensor",
    "discovery_device_name": "TheengsGateway",
    "discovery_filter": "[TP357]",
    "scanning_mode": "active",
    "adapter": "hci0",
    "time_sync": "[]",
    "time_format": "0"
}
INFO:BLEGateway:Starting BLE scan
INFO:BLEGateway:Connected to MQTT Broker!
INFO:BLEGateway:Subscribed to TheengsGateway/BTtoMQTT/set
```

**Comment by gmallapp** [comment]
I had the same issue just now. after some tinkering, changing the environment variables to the below worked for me
   MQTT_HOST: 127.0.0.1
   MQTT_USERNAME: uuuu
   MQTT_PASSWORD: ####
   MQTT_PUB_TOPIC: TheengsGateway/BTtoMQTT
   MQTT_SUB_TOPIC: TheengsGateway/BTtoMQTT/set
   MQTT_PRE_TOPIC: TheengsGateway/BTtoMQTT
   LWT_TOPIC: TheengsGateway/LWT
   PUBLISH_ALL: true
   PUBLISH_ADVDATA: false
   TIME_BETWEEN: 60
   SCAN_TIME: 60
   LOG_LEVEL: INFO
   HAAS_DISCOVERY: false
   DISCOVERY: false
   DISCOVERY_TOPIC: homeassistant/sensor
   DISCOVERY_DEVICE_NAME: TheengsGateway
   DISCOVERY_FILTER: "[TP357]"
   SCANNING_MODE: active
   ADAPTER: hci0

**Comment by universal-dilettant** [comment]
@gmallapp 
Your answer is much appreciated, thank you. However...
I'm not excluding that I'm missing something.

- What have you changed and where? What did you tinker with?
- The ENV itself looks the same as the one I've posted. Where is the difference?

**Comment by gmallapp** [comment]
The format you had used (and what I used when I was trying to bring this container up the first time) is:
```
environment:
      - MQTT_HOST=127.0.0.1
      - MQTT_USERNAME=uuuu
      - MQTT_PASSWORD=####
      - MQTT_PUB_TOPIC=TheengsGateway/BTtoMQTT
```
It's typically an accepted format for env variables and i've used this everywhere for my other containers in the docker-compose file. This format, using "=" passes a string and docker does some magic to split this string and assign the key value pair to environment variables.

The change I made is use the yaml native syntax for the environment variable mapping (key: value):
```
environment:
    MQTT_HOST: 127.0.0.1
    MQTT_USERNAME: uuuu
    MQTT_PASSWORD: ####
    MQTT_PUB_TOPIC: TheengsGateway/BTtoMQTT
```
